# Generated by Django 5.2.5 on 2025-08-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0003_congratulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congratulation',
            options={'ordering': ('created_at',)},
        ),
    ]
